"""Request-parameter surface for the playground.

Rendered from the target server's own /openapi.json, so the controls match what
that build accepts. vLLM moves these around between releases — 0.24 replaced the
guided_json/guided_regex family with a single structured_outputs object — and a
hand-maintained list would quietly drift. A snapshot generated by
tools/gen_sampling_schema.py ships as the fallback for when nothing is running.
"""

from __future__ import annotations

import json
import time
from functools import lru_cache
from typing import Any

import httpx

from app.config import settings

CACHE_TTL = 300.0
_cache: dict[str, tuple[float, dict]] = {}

# Controls promoted to the main panel, in the order they belong there. The rest
# stay reachable under "All parameters".
FEATURED: list[dict[str, Any]] = [
    {
        "id": "core",
        "title": "Sampling",
        "fields": [
            "temperature", "top_p", "top_k", "min_p", "max_tokens", "seed", "n",
        ],
    },
    {
        "id": "penalties",
        "title": "Repetition control",
        "fields": [
            "repetition_penalty", "presence_penalty", "frequency_penalty",
            "length_penalty", "min_tokens", "ignore_eos",
        ],
    },
    {
        "id": "stopping",
        "title": "Stopping",
        "fields": ["stop", "stop_token_ids", "include_stop_str_in_output", "bad_words"],
    },
    {
        "id": "reasoning",
        "title": "Reasoning & templates",
        "fields": [
            "include_reasoning", "reasoning_effort", "thinking_token_budget",
            "chat_template_kwargs", "add_generation_prompt", "continue_final_message",
        ],
    },
    {
        "id": "structured",
        "title": "Structured output",
        "fields": ["structured_outputs", "response_format"],
    },
    {
        "id": "tools",
        "title": "Tools",
        "fields": ["tools", "tool_choice", "parallel_tool_calls"],
    },
    {
        "id": "introspection",
        "title": "Introspection",
        "fields": [
            "logprobs", "top_logprobs", "prompt_logprobs", "echo",
            "return_token_ids", "skip_special_tokens",
        ],
    },
]

# Sliders need bounds the schema does not carry.
HINTS: dict[str, dict[str, Any]] = {
    "temperature": {"min": 0.0, "max": 2.0, "step": 0.01, "suggested": 0.7},
    "top_p": {"min": 0.0, "max": 1.0, "step": 0.01, "suggested": 1.0},
    "top_k": {"min": -1, "max": 200, "step": 1, "suggested": -1},
    "min_p": {"min": 0.0, "max": 1.0, "step": 0.01, "suggested": 0.0},
    "repetition_penalty": {"min": 0.5, "max": 2.0, "step": 0.01, "suggested": 1.0},
    "presence_penalty": {"min": -2.0, "max": 2.0, "step": 0.01},
    "frequency_penalty": {"min": -2.0, "max": 2.0, "step": 0.01},
    "max_tokens": {"min": 1, "max": 262144, "step": 1, "suggested": 1024},
    "n": {"min": 1, "max": 8, "step": 1},
    "top_logprobs": {"min": 0, "max": 20, "step": 1},
}

# Set by the transport, not by the user.
HIDDEN = {
    "messages", "prompt", "model", "stream", "stream_options", "request_id",
    "user", "kv_transfer_params", "vllm_xargs", "cache_salt", "priority",
}


@lru_cache(maxsize=1)
def fallback() -> dict:
    path = settings.data_dir / "sampling_params.json"
    if not path.exists():
        return {"requests": {}, "structured_outputs": {}, "paths": []}
    return json.loads(path.read_text())


async def fetch(base_url: str) -> dict:
    """Read a server's schema, memoised briefly so a chatty UI is cheap."""
    now = time.monotonic()
    hit = _cache.get(base_url)
    if hit and now - hit[0] < CACHE_TTL:
        return hit[1]

    from tools.gen_sampling_schema import extract  # local import: tool code, not runtime code

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(f"{base_url.rstrip('/')}/openapi.json")
        response.raise_for_status()
        payload = extract(response.json())
        if not payload.get("requests"):
            raise ValueError("no request schema")
        payload["source"] = base_url
    except Exception:
        payload = {**fallback(), "source": "bundled snapshot"}

    _cache[base_url] = (now, payload)
    return payload


def ui_model(payload: dict, request_name: str = "ChatCompletionRequest") -> dict:
    model = payload.get("requests", {}).get(request_name, {})
    fields: dict[str, Any] = dict(model.get("fields", {}))

    def decorate(name: str) -> dict:
        entry = dict(fields.get(name, {}))
        entry["name"] = name
        entry.update(HINTS.get(name, {}))
        if name == "structured_outputs":
            entry["structured_options"] = payload.get("structured_outputs", {})
        return entry

    used: set[str] = set()
    sections = []
    for section in FEATURED:
        present = [name for name in section["fields"] if name in fields]
        if not present:
            continue
        used.update(present)
        sections.append({**section, "fields": [decorate(name) for name in present]})

    rest = sorted(name for name in fields if name not in used and name not in HIDDEN)
    return {
        "source": payload.get("source", ""),
        "paths": payload.get("paths", []),
        "featured": sections,
        "advanced": [decorate(name) for name in rest],
        "hidden": sorted(HIDDEN),
    }
